subscription:
  - name: Eternally Regressing Knight
    url: https://w8.regressingknight.com/eternally-regressing-knight-chapter-{chapter}/
    notify: true
  - name: Pick Me Up Infinite Gacha
    url: https://w13.pickmeupgacha.com/pick-me-up-infinite-gacha-chapter-{chapter}/
    notify: true
  - name: Star-Embracing Swordmaster
    url: https://manhuaus.com/manga/star-embracing-swordmaster/chapter-{chapter}/
    notify: true
  - name: The Regressed Mercenary's Machinations
    url: https://manhuaus.com/manga/the-regressed-mercenarys-machinations/chapter-{chapter}/
    notify: true
